import "./globals.css";
import { Poppins } from "next/font/google";

const popins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "First App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <main className="container">
          {children}
        </main>
        </body>
    </html>
  );
}
